### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by laszewsk** [cybertraining-dsc/sp20-523-305#3]
Please be reminded that you are responsible for your pull requests

see: https://github.com/cybertraining-dsc/fa20-523-305/pulls

you probably know this, but I just want to make sure

**Comment by codyharris91** [comment]
I do not think I have write access to accomplish this.

**Comment by laszewsk** [comment]
You do, please attend office hours

**Comment by codyharris91** [comment]
Okay, I will attend today
